### PR TITLE
fixed grammatical error

### PR DESCRIPTION
**Pull request by Ganofins**

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
How did you find this repo ? :-)

**Comment by drupol** [comment]
It's not even published yet !

**Comment by Ganofins** [comment]
> How did you find this repo ? :-)

I am following you 🤗

**Comment by drupol** [comment]
Ok ok ! Thanks mate!

I will publish a fixed release of this today ;-)

**Pull request merged**
